# Generated by Django 2.1.5 on 2022-03-03 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import signuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('eu_id', models.AutoField(primary_key=True, serialize=False)),
                ('eu_headerimg', models.ImageField(blank=True, default='static/images/head_img.jpg', null=True, upload_to=signuser.models.eu_header_img)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
