# Generated by Django 2.1.5 on 2022-03-03 23:51

from django.db import migrations, models
import signuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('signuser', '0002_auto_20220303_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='eu_headerimg',
            field=models.ImageField(blank=True, default='/images/head_img.jpg', null=True, upload_to=signuser.models.eu_header_img),
        ),
    ]
