# Generated by Django 2.1.5 on 2022-03-04 01:27

from django.db import migrations, models
import signuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('signuser', '0007_auto_20220304_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='eu_headerimg',
            field=models.ImageField(blank=True, default='/media/images/logo.jpg', null=True, upload_to=signuser.models.eu_header_img),
        ),
    ]
