# Generated by Django 2.1.5 on 2022-03-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuser', '0009_auto_20220304_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='eu_headerimg',
            new_name='header_img',
        ),
    ]
